### PR TITLE
fix CORS and SAML config for login UI

### LINKED ISSUE #45: more streamlined CORS solution
right now our config to allow CORS is split between nginx and Rails. I think it will be easier to manage if we just use https://github.com/cyu/rack-cors

### PR DESCRIPTION
**Pull request by shauni**
fixes #45

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -1,7 +1,5 @@
 # frozen_string_literal: true
 Rails.application.routes.draw do
-  # TODO(#45): add rack-cors middleware to streamline CORS config
-  # Adding CORS preflight routes here for now to unblock front-end dev
   match '/v0/*path', to: 'application#cors_preflight', via: [:options]
```
Comment (omgitsbillryan) [inline config/routes.rb]: Is this route still required?  Also, what does `:options` mean?

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -7,7 +7,6 @@ class ApplicationController < ActionController::API
   before_action :set_app_info_headers
   skip_before_action :authenticate, only: [:cors_preflight]
 
-  # TODO(shauni #45) - replace with rack-cors
   def cors_preflight
```
Comment (omgitsbillryan) [inline app/controllers/application_controller.rb]: Still intend to replace with rack-cors?

File: config/application.yml.example [hunk 3]
```diff
@@ -18,3 +18,6 @@ EVSS_CLAIMS_BASE_URL: 'http://csraciapp6.evss.srarad.com:7003/wss-claims-service
 EVSS_DOCUMENTS_BASE_URL: 'http://csraciapp6.evss.srarad.com:7003/wss-document-services-web-3.1/rest/'
 EVSS_SAMPLE_CLAIMANT_USER: '{"first_name": "Jane","last_name": "Doe","edipi": "1105051936","participant_id": "123456789"}'
 MVI_URL: 'http://ps-dev.commserv.healthevet.va.gov:8110/psim_webservice/IdMWebService'
+
+# For CORS requests; separate multiple origins with a comma
+WEB_ORIGIN: 'http://localhost:3000,http://localhost:3001'
```
Comment (omgitsbillryan) [inline config/application.yml.example]: Is this only for local development purposes?

File: config/routes.rb (hunk 1 above)
Comment (shauni) [inline config/routes.rb]: I previously thought that the rack-cors gem would take care of handling preflight requests, but it turns out we still need to have a route/action to handle them. OPTIONS is the request method (instead of GET, POST, etc).

see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests for more info.

File: app/controllers/application_controller.rb (hunk 2 above)
Comment (shauni) [inline app/controllers/application_controller.rb]: see comment above.

File: config/application.yml.example (hunk 3 above)
Comment (shauni) [inline config/application.yml.example]: no - on dev, staging and prod, since the AJAX requests will be coming from a different origin from the API (www.vets.gov vs api.vets.gov) we'll need to specify these per environment.

File: app/controllers/v0/sessions_controller.rb [hunk 4]
```diff
@@ -27,7 +27,7 @@ def saml_callback
         render json: @session, status: :created
       else
         # TODO: also need to make sure error json conforms to api spec
-        render json: { errors: @saml_response.errors.full_messages }, status: :forbidden
+        render json: { errors: @saml_response.errors }, status: :forbidden
```
Comment (carlmjohnson) [inline app/controllers/v0/sessions_controller.rb]: If you raise a subclass of `Common::Exceptions::BaseError`, our application rescue_from will render it as JSON-API style JSON.

Comment (shauni) [inline app/controllers/v0/sessions_controller.rb]: awesome! will add that in a separate PR :)
